import type { SeedCall } from "./seed"

const transcript: SeedCall["transcript"] = [
  { id: "turn-1", speaker: "employee", startSeconds: 0, text: "Thank you for calling ACME Support. This is Riley. How can I help you today?" },
  { id: "turn-2", speaker: "customer", startSeconds: 6, text: "Hi, our storefront security hub went offline overnight, and none of the door sensors are reporting. We open in about forty minutes." },
  { id: "turn-3", speaker: "employee", startSeconds: 13, text: "That normally points to an internet outage. You will probably need to restart the router and wait ten minutes for everything to reconnect." },
  { id: "turn-4", speaker: "customer", startSeconds: 22, text: "The internet is working. Our registers, phones, and guest Wi-Fi are all online, and I have already restarted the router twice because the last agent told me to." },
  { id: "turn-5", speaker: "employee", startSeconds: 30, text: "The hub can still lose its connection even when other devices work, so another restart is usually the fastest next step." },
  { id: "turn-6", speaker: "customer", startSeconds: 37, text: "This is exactly why I called instead of reading the help page. Repeating the same restart is not helping, and I need someone to actually look at what the hub is doing." },
  { id: "turn-7", speaker: "employee", startSeconds: 46, text: "You are right. I jumped to the standard answer without listening to what you had already tested, and I am sorry." },
  { id: "turn-8", speaker: "employee", startSeconds: 53, text: "Let me start again. Your network is otherwise healthy, the hub and door sensors stopped reporting overnight, and opening time is close. Is that accurate?" },
  { id: "turn-9", speaker: "customer", startSeconds: 62, text: "Yes, exactly. We can unlock the doors manually, but I am not willing to open a store with no alarm, and staff are arriving any minute." },
  { id: "turn-10", speaker: "employee", startSeconds: 70, text: "That makes sense. Before I access the security device records, may I verify the site nickname, billing postal code, and support PIN?" },
  { id: "turn-11", speaker: "customer", startSeconds: 78, text: "The site is Harbor Street Shop, the postal code is 97205, and the support PIN is 7316." },
  { id: "turn-12", speaker: "employee", startSeconds: 85, text: "Thank you. All three match, so I can view the hub diagnostics and make changes with your approval." },
  { id: "turn-13", speaker: "employee", startSeconds: 92, text: "When did you first notice the outage, and did anything change in the store network yesterday?" },
  { id: "turn-14", speaker: "customer", startSeconds: 99, text: "The last normal alert was around eleven last night. An installer replaced our network switch yesterday afternoon, but everything worked when we closed." },
  { id: "turn-15", speaker: "employee", startSeconds: 107, text: "That change may be relevant. What does the hub display show now, including any error code and the color of its status light?" },
  { id: "turn-16", speaker: "customer", startSeconds: 116, text: "The light alternates blue and amber. The app shows Gateway unavailable, then error E-42 when I tap diagnostics." },
  { id: "turn-17", speaker: "employee", startSeconds: 123, text: "I see the E-42 events. The hub is reaching ACME every few minutes, so the earlier internet-outage assumption was incorrect." },
  { id: "turn-18", speaker: "customer", startSeconds: 131, text: "That worries me. Does the occasional connection mean the alarm still works, or have we been sitting here completely unprotected all night?" },
  { id: "turn-19", speaker: "employee", startSeconds: 139, text: "I do not want to guess about that. The local siren may still trigger, but remote monitoring is not confirmed while the hub shows unavailable." },
  { id: "turn-20", speaker: "customer", startSeconds: 147, text: "Thank you for being clear. What can we check without wiping all thirty sensors and starting over?" },
  { id: "turn-21", speaker: "employee", startSeconds: 155, text: "We will avoid a factory reset. First, please open Settings, Network, and tell me whether the hub lists an address beginning with 169 or 192." },
  { id: "turn-22", speaker: "customer", startSeconds: 164, text: "It starts with 192.168, and below that it says Time synchronization failed." },
  { id: "turn-23", speaker: "employee", startSeconds: 171, text: "That narrows it down. The hub has a local address, but its clock is almost nine hours behind, which can invalidate its security certificate." },
  { id: "turn-24", speaker: "customer", startSeconds: 180, text: "Could the new switch cause the clock problem even though it did not fail immediately?" },
  { id: "turn-25", speaker: "employee", startSeconds: 187, text: "Yes. The switch may be blocking the time-service request, and the hub continued using its cached certificate until that certificate check renewed overnight." },
  { id: "turn-26", speaker: "customer", startSeconds: 196, text: "I can sign in to the switch dashboard, but I am not comfortable changing random network rules." },
  { id: "turn-27", speaker: "employee", startSeconds: 204, text: "Please do not change anything yet. I am comparing the failed requests with our approved network checklist so we make one controlled change." },
  { id: "turn-28", speaker: "customer", startSeconds: 212, text: "All right. I appreciate that because the registers are on the same switch." },
  { id: "turn-29", speaker: "employee", startSeconds: 219, text: "The logs show time traffic is blocked on the hub port. Do you see a profile called Restricted Devices assigned to port twelve?" },
  { id: "turn-30", speaker: "customer", startSeconds: 227, text: "Yes, port twelve says Restricted Devices. The installer must have applied that profile when they moved the cable." },
  { id: "turn-31", speaker: "employee", startSeconds: 236, text: "That profile blocks the time service the hub needs. Select Standard IoT, but do not save yet; I want to confirm the other settings first." },
  { id: "turn-32", speaker: "customer", startSeconds: 244, text: "Standard IoT is selected. The screen says it will briefly reconnect anything on that port." },
  { id: "turn-33", speaker: "employee", startSeconds: 252, text: "Correct. Only the security hub is on port twelve according to our device record, so the registers should remain online." },
  { id: "turn-34", speaker: "customer", startSeconds: 261, text: "I have the save button ready. Are you certain this will bring every sensor back?" },
  { id: "turn-35", speaker: "employee", startSeconds: 268, text: "Yes, once you save it I can have the whole system restored within five minutes." },
  { id: "turn-36", speaker: "customer", startSeconds: 276, text: "Hold on. A minute ago you said the sensors might have separate issues, and now it is five minutes for all of them. Which is it?" },
  { id: "turn-37", speaker: "employee", startSeconds: 284, text: "No, and I need to correct what I just said. The change should restore the hub connection, but I cannot guarantee every sensor until we see them report." },
  { id: "turn-38", speaker: "employee", startSeconds: 293, text: "I am sorry for giving you an unsupported time promise. If you approve, save the profile and I will watch the hub telemetry with you." },
  { id: "turn-39", speaker: "customer", startSeconds: 301, text: "I appreciate you correcting that instead of letting me find out later. I have saved the change, and the hub light is solid amber now." },
  { id: "turn-40", speaker: "employee", startSeconds: 309, text: "I see the time request succeed. The clock is correcting now, and the hub has started a fresh certificate handshake." },
  { id: "turn-41", speaker: "customer", startSeconds: 317, text: "The app changed from unavailable to reconnecting. Is there anything I should avoid touching while it does that?" },
  { id: "turn-42", speaker: "employee", startSeconds: 325, text: "Leave the hub powered and keep the app open. Please do not press the recessed reset button; that would erase the sensor pairing." },
  { id: "turn-43", speaker: "customer", startSeconds: 333, text: "Understood. The front door and office motion sensor just turned green, but most of the list is still gray." },
  { id: "turn-44", speaker: "employee", startSeconds: 341, text: "That is useful progress. The hub connection is restored, and battery sensors report on their next check-in rather than all at once." },
  { id: "turn-45", speaker: "customer", startSeconds: 349, text: "The loading door matters most. Can we check that one specifically before staff arrive?" },
  { id: "turn-46", speaker: "employee", startSeconds: 357, text: "Yes. Without opening the door, press its test button once and tell me whether the sensor flashes." },
  { id: "turn-47", speaker: "customer", startSeconds: 364, text: "It flashed red twice, and now the app says low battery instead of offline." },
  { id: "turn-48", speaker: "employee", startSeconds: 371, text: "The network issue was hiding a separate low battery. That sensor cannot be considered reliable until the battery is replaced." },
  { id: "turn-49", speaker: "customer", startSeconds: 379, text: "We have the correct batteries in the supply cabinet. Can I replace it while you stay on the line?" },
  { id: "turn-50", speaker: "employee", startSeconds: 387, text: "Yes. Put the system in maintenance mode first so opening the sensor case does not create a tamper alarm." },
  { id: "turn-51", speaker: "customer", startSeconds: 394, text: "Maintenance mode is on. I replaced the battery, closed the case, and the loading door now shows green." },
  { id: "turn-52", speaker: "employee", startSeconds: 401, text: "I can confirm its check-in and battery level. Please take the system out of maintenance mode, then arm it in Stay mode." },
  { id: "turn-53", speaker: "customer", startSeconds: 409, text: "It armed, but the stockroom window is still offline. That one is high up and I am not getting on a ladder minutes before we open." },
  { id: "turn-54", speaker: "employee", startSeconds: 417, text: "Do not climb to reach it. I am escalating that sensor to our device team while we confirm whether its last signal suggests a battery or radio problem." },
  { id: "turn-55", speaker: "customer", startSeconds: 425, text: "So are we back where we started? I need a straight answer on whether it is safe to open with that one offline." },
  { id: "turn-56", speaker: "employee", startSeconds: 433, text: "Remote monitoring and the other twenty-nine sensors are active. The stockroom window is the one known gap, and I will document it clearly rather than call the system fully restored." },
  { id: "turn-57", speaker: "customer", startSeconds: 442, text: "That distinction helps. The stockroom window is behind a locked interior door, so we can keep that room closed today." },
  { id: "turn-58", speaker: "employee", startSeconds: 451, text: "That is a reasonable temporary measure. I have device specialist Morgan joining the case now, and I am sharing the diagnostics so you do not repeat the story." },
  { id: "turn-59", speaker: "customer", startSeconds: 459, text: "We are at opening time now. What happens next, and how do I know someone actually follows up instead of this sitting in a queue?" },
  { id: "turn-60", speaker: "employee", startSeconds: 468, text: "Your case is AC-80419. I scheduled an onsite sensor visit for tomorrow between nine and eleven, subject to the confirmation email arriving in a moment." },
  { id: "turn-61", speaker: "employee", startSeconds: 477, text: "I also set a two-hour monitoring check. I will call the store at noon if the stockroom sensor has not reported or if any restored sensor drops again." },
  { id: "turn-62", speaker: "customer", startSeconds: 487, text: "Please use the store number already on the account. I do not want personal contact details added just for this case." },
  { id: "turn-63", speaker: "employee", startSeconds: 495, text: "Understood. I will use only the verified store number and will not add or disclose any new contact information." },
  { id: "turn-64", speaker: "customer", startSeconds: 503, text: "The appointment email just arrived. It says nine to eleven and lists the stockroom window sensor." },
  { id: "turn-65", speaker: "employee", startSeconds: 511, text: "Good. I am adding the switch-profile correction, battery replacement, current monitoring status, and the remaining sensor gap to the same case." },
  { id: "turn-66", speaker: "customer", startSeconds: 520, text: "What stops the installer from putting that restricted profile straight back when they return to finish their work?" },
  { id: "turn-67", speaker: "employee", startSeconds: 528, text: "They could, so I am emailing you ACME's network requirements and a note naming port twelve and the Standard IoT profile." },
  { id: "turn-68", speaker: "customer", startSeconds: 538, text: "I can give that to them. The dashboard now shows monitoring active with one sensor warning." },
  { id: "turn-69", speaker: "employee", startSeconds: 545, text: "That matches my view. Before we finish, I want to summarize: the hub is online, monitoring is active, and twenty-nine sensors are reporting." },
  { id: "turn-70", speaker: "employee", startSeconds: 555, text: "The stockroom window remains offline behind a locked room, tomorrow's visit is confirmed, and I own the noon status call under case AC-80419." },
  { id: "turn-71", speaker: "customer", startSeconds: 564, text: "Yes, that is accurate. I was frustrated at the beginning, but this gives me a clear way to open safely." },
  { id: "turn-72", speaker: "employee", startSeconds: 572, text: "I understand, and you should not have had to push past my first assumption. Thank you for working through the diagnosis with me." },
  { id: "turn-73", speaker: "customer", startSeconds: 581, text: "Thank you for admitting that and staying with it. I have the case number, the appointment, and the network note." },
  { id: "turn-74", speaker: "employee", startSeconds: 589, text: "You are welcome. I will keep ownership through the noon check, and ACME Support will contact you sooner if monitoring changes." },
]

export const longDemoCall: SeedCall = {
  id: "call-1009",
  customerName: "Dana Ortiz",
  agentName: "Riley Chen",
  subject: "Long call · Store security hub outage after network change",
  startedAt: "2026-09-16T12:30:00.000Z",
  durationSeconds: 600,
  transcript,
}
