import type { Criterion, TranscriptTurn } from "@scorecard/domain"
import { longDemoCall } from "./long-call"

export interface SeedCall {
  readonly id: string
  readonly customerName: string
  readonly agentName: string
  readonly subject: string
  readonly startedAt: string
  readonly durationSeconds: number
  readonly transcript: ReadonlyArray<TranscriptTurn>
}

const turns = (
  entries: ReadonlyArray<readonly ["customer" | "employee", string, number]>,
): ReadonlyArray<TranscriptTurn> =>
  entries.map(([speaker, text, startSeconds], index) => ({
    id: `turn-${index + 1}`,
    speaker,
    text,
    startSeconds,
  }))

export const seedCalls: ReadonlyArray<SeedCall> = [
  {
    id: "call-1001",
    customerName: "Maya Chen",
    agentName: "Jordan Lee",
    subject: "Duplicate subscription charge",
    startedAt: "2026-09-15T14:05:00.000Z",
    durationSeconds: 316,
    transcript: turns([
      ["employee", "ACME Support, this is Jordan. What can I help you with today?", 0],
      ["customer", "I was charged twice for my annual plan and I am pretty frustrated.", 14],
      ["employee", "Duplicate charges are usually temporary authorizations. Your bank should remove one in a few days.", 29],
      ["customer", "My bank says both charges settled. I need you to look instead of sending me back to them.", 43],
      ["employee", "You’re right. I dismissed this too quickly, and I’m sorry. I’ll take ownership and review both transactions now.", 57],
      ["employee", "Before I open the billing details, may I verify the postal code and the month your plan renews?", 72],
      ["customer", "The postal code is 02139, and it renews in September.", 85],
      ["employee", "Thank you, that matches the account. About when did each charge appear?", 97],
      ["customer", "One appeared Monday morning and the other Monday afternoon. They are both for $129.", 110],
      ["employee", "I see them. One is the scheduled renewal and the second is a posted duplicate, so this isn’t a temporary authorization.", 125],
      ["customer", "That’s what I was trying to explain.", 139],
      ["employee", "I understand, and I appreciate you correcting me. I’m checking whether I can reverse it immediately rather than open a longer dispute.", 150],
      ["customer", "I would really prefer that. The extra charge affected another payment.", 163],
      ["employee", "Understood. I have approval to refund the duplicate $129 charge to the original payment method.", 174],
      ["customer", "When should I expect to see it?", 188],
      ["employee", "ACME is releasing it today. Most banks post it in three to five business days, though your bank controls the final timing.", 200],
      ["customer", "Can you make sure this won’t happen again next year?", 216],
      ["employee", "Yes. I removed the duplicate renewal record and confirmed there is now one active annual subscription on the account.", 229],
      ["customer", "Okay. Can you send me something in writing?", 243],
      ["employee", "Absolutely. I just sent a confirmation with refund reference RF-4821 and the expected time frame.", 256],
      ["customer", "I see the email. Does cancelling the duplicate affect my service?", 270],
      ["employee", "No. Your primary subscription remains active through next September; only the duplicate transaction was reversed.", 282],
      ["customer", "That clears it up. Thanks for turning this around.", 296],
      ["employee", "You’re welcome, and thank you for giving me the chance to correct my first response.", 307],
    ]),
  },
  {
    id: "call-1002",
    customerName: "Robert Davis",
    agentName: "Avery Morgan",
    subject: "Cannot connect smart hub",
    startedAt: "2026-09-15T16:40:00.000Z",
    durationSeconds: 542,
    transcript: turns([
      ["employee", "ACME Support, Avery speaking. I’m happy to help. What is happening with your device?", 0],
      ["customer", "My hub has been offline since yesterday. I already restarted it twice.", 11],
      ["employee", "Thanks for telling me what you already tried. I won’t ask you to repeat those restarts.", 27],
      ["employee", "Before I access the device controls, can you confirm the account nickname and postal code?", 41],
      ["customer", "The nickname is Home Hub and the postal code is 98109.", 55],
      ["employee", "That matches. What color is the hub light, and is it steady or blinking?", 68],
      ["customer", "It is blinking amber.", 82],
      ["employee", "Thank you. I can see an H-17 event after a failed firmware update, so your internet connection may be fine.", 97],
      ["customer", "That makes sense. My laptop and phone are both online.", 114],
      ["employee", "I’ll send a firmware recovery command instead of resetting your router.", 128],
      ["customer", "Will that erase my device settings?", 141],
      ["employee", "No. This recovery keeps your automations and paired devices in place.", 154],
      ["customer", "Great. How long does it usually take?", 167],
      ["employee", "Usually ten to twenty minutes. I’ll stay with you while we confirm it begins.", 179],
      ["customer", "The light just stopped blinking, but it is still amber.", 197],
      ["employee", "That means the recovery was accepted. The next stage should turn it blue.", 210],
      ["customer", "I need to leave soon. Can my partner call if it does not finish?", 225],
      ["employee", "Yes, I can add them now. Just give me their full name and email address.", 239],
      ["customer", "Don’t they need to verify themselves before you add access?", 254],
      ["employee", "For a small change like this, the email is enough. It will save time later.", 269],
      ["customer", "I’m not comfortable changing account access without verification.", 284],
      ["employee", "Okay, we can skip that. I can guarantee the hub will be back online within ten minutes anyway.", 299],
      ["customer", "You said it usually takes up to twenty minutes. Is ten really guaranteed?", 315],
      ["employee", "The command has started, so yes, ten minutes should be certain.", 330],
      ["customer", "Please give me a case number in case that prediction is wrong.", 344],
      ["employee", "The case is TH-7714. If it is still offline later, anyone in the household can quote that number.", 358],
      ["customer", "I’ll keep the number, but please do not add or discuss my account with anyone who is not verified.", 376],
      ["employee", "All right. The recovery is running, and the case notes say you requested a callback if it fails.", 392],
    ]),
  },
  {
    id: "call-1003",
    customerName: "Elena García",
    agentName: "Jordan Lee",
    subject: "Change delivery address",
    startedAt: "2026-09-14T19:12:00.000Z",
    durationSeconds: 228,
    transcript: turns([
      ["employee", "Thank you for calling ACME Support. My name is Jordan. May I have your order number?", 0],
      ["customer", "It’s NS-77342. I need the delivery address changed before it ships.", 12],
      ["employee", "For security, can you confirm the email and postal code on the order?", 29],
      ["customer", "elena@example.com and 10011.", 44],
      ["employee", "Thank you. I updated the address to the Brooklyn location you provided and emailed the revised order.", 83],
      ["customer", "Perfect, thank you for making that easy.", 112],
      ["employee", "You’re welcome. Your delivery date remains Friday. Have a great evening.", 124],
    ]),
  },
  {
    id: "call-1004",
    customerName: "Noah Williams",
    agentName: "Sam Patel",
    subject: "Unexpected roaming fees",
    startedAt: "2026-09-14T13:30:00.000Z",
    durationSeconds: 455,
    transcript: turns([
      ["employee", "ACME Support billing, this is Sam. How may I assist?", 0],
      ["customer", "My bill has $86 in roaming charges that I was told were included.", 13],
      ["employee", "The charges are valid according to the system.", 31],
      ["customer", "The sales representative explicitly said Canada was included.", 47],
      ["employee", "I understand that is what you remember, but your plan does not show it.", 68],
      ["customer", "Can you review the original order or ask a supervisor?", 90],
      ["employee", "I can open a billing investigation. You’ll receive a decision in seven to ten days.", 123],
      ["customer", "Please do, and give me the case number.", 149],
      ["employee", "The case is BI-9017. You will get an email update.", 163],
    ]),
  },
  {
    id: "call-1005",
    customerName: "Priya Shah",
    agentName: "Avery Morgan",
    subject: "Cancel trial before renewal",
    startedAt: "2026-09-13T10:18:00.000Z",
    durationSeconds: 267,
    transcript: turns([
      ["employee", "ACME Support, Avery here. How can I help?", 0],
      ["customer", "I want to cancel my trial before it renews tomorrow.", 10],
      ["employee", "I can take care of that. Could you confirm the last four digits of the card?", 20],
      ["customer", "4428.", 31],
      ["employee", "Thanks. The trial is cancelled, there will be no renewal charge, and your access ends tonight at midnight.", 52],
      ["customer", "That’s all I needed.", 79],
      ["employee", "I’ve also sent a cancellation email. Thank you for trying ACME.", 88],
    ]),
  },
  {
    id: "call-1006",
    customerName: "Marcus Johnson",
    agentName: "Sam Patel",
    subject: "Missing replacement device",
    startedAt: "2026-09-12T21:06:00.000Z",
    durationSeconds: 603,
    transcript: turns([
      ["employee", "Thank you for calling ACME Support, Sam speaking.", 0],
      ["customer", "My replacement was promised Monday. Tracking still says label created.", 9],
      ["employee", "I’m sorry you’ve been waiting. Let me check the warehouse status and the carrier scan.", 24],
      ["employee", "First, may I confirm the delivery postal code and the last two characters of the original order number?", 39],
      ["customer", "The postal code is 60614 and the order ends in K7.", 53],
      ["employee", "Thank you. I found the replacement order. It was packed Friday, but there is no carrier acceptance scan.", 69],
      ["customer", "That’s what I was afraid of. The device is how I connect to my work system.", 84],
      ["employee", "I understand why the delay is urgent. I’m checking the warehouse exception queue before I promise a delivery date.", 100],
      ["customer", "The last agent promised Monday and then nothing changed.", 118],
      ["employee", "I’m sorry we set that expectation without confirming a scan. I can see the package is still at our warehouse, and I’m escalating this to the logistics lead now.", 135],
      ["customer", "Can the same box be sent tonight?", 151],
      ["employee", "The carrier cutoff has passed, so I can’t honestly guarantee movement tonight.", 166],
      ["customer", "What can you do instead?", 179],
      ["employee", "The logistics lead approved a new priority replacement for the morning pickup and cancellation of the stalled shipment.", 193],
      ["customer", "Would that arrive tomorrow?", 207],
      ["employee", "Tomorrow is possible, but I can only guarantee dispatch in the morning. The carrier estimate will appear after its first scan.", 222],
      ["customer", "I’d rather have the realistic answer. Please send the new one.", 239],
      ["employee", "I’ll do that now. There is no shipping charge, and I’m also applying a one-month service credit for the delay.", 253],
      ["customer", "Thank you. What happens to the first package if it starts moving?", 270],
      ["employee", "I’m marking it return-to-sender. If it still reaches you, the email will include a prepaid return label.", 285],
      ["customer", "Okay. Can you give me the new order number?", 303],
      ["employee", "The new order is NS-99831. I’m reading it back: N-S, nine-nine-eight-three-one.", 316],
      ["customer", "Got it.", 331],
      ["employee", "I have also scheduled a check for tomorrow morning. If there is no carrier scan by 10 a.m., our team will contact you.", 340],
      ["customer", "That follow-up would help. I don’t want to start over again.", 358],
      ["employee", "You won’t need to. The replacement, service credit, and follow-up are all under case RS-2046.", 373],
      ["customer", "I appreciate you explaining what you can and cannot guarantee.", 389],
      ["employee", "You’re welcome. I’ve emailed the case and order details. Is there anything else I can address while I have the account open?", 405],
      ["customer", "No, that covers it.", 423],
    ]),
  },
  {
    id: "call-1007",
    customerName: "Taylor Brooks",
    agentName: "Sam Patel",
    subject: "Account email changed without verification",
    startedAt: "2026-09-12T15:22:00.000Z",
    durationSeconds: 344,
    transcript: turns([
      ["employee", "ACME Support account team, Sam speaking. What do you need changed?", 0],
      ["customer", "I lost access to my old email and need the account moved to taylor.new@example.com.", 12],
      ["employee", "Okay, what is the old email?", 28],
      ["customer", "tbrooks@example.com.", 37],
      ["employee", "I found it. I changed the login email and sent a password reset to the new address.", 61],
      ["customer", "Don’t you need to verify my identity first?", 82],
      ["employee", "The old email matched, so you’re all set.", 96],
      ["customer", "That seems unsafe, but okay.", 111],
    ]),
  },
  {
    id: "call-1008",
    customerName: "Amara Okafor",
    agentName: "Jordan Lee",
    subject: "Accessibility issue in mobile checkout",
    startedAt: "2026-09-11T17:48:00.000Z",
    durationSeconds: 518,
    transcript: turns([
      ["employee", "Thank you for contacting ACME Support. This is Jordan. How may I help?", 0],
      ["customer", "The checkout button has no label in my screen reader, so I can’t finish an order.", 13],
      ["employee", "I’m sorry our checkout blocked you. Thank you for explaining the accessibility issue clearly.", 31],
      ["employee", "I can place the order with you now, and I’d also like to document the exact app version for our accessibility team. Is that okay?", 52],
      ["customer", "Yes. I’m on version 8.4 on Android.", 73],
      ["employee", "Thank you. I verified your shipping details, placed the order at the online price, and waived shipping. Your confirmation is NS-31482.", 126],
      ["employee", "I opened accessibility case AX-204. I’ll email you by Friday with the engineering update, even if the fix is still in progress.", 161],
      ["customer", "That’s exactly what I needed. Thanks for taking it seriously.", 198],
      ["employee", "You’re welcome. The confirmation and case number are in your inbox now.", 212],
    ]),
  },
  longDemoCall,
]

const updatedAt = "2026-09-16T00:00:00.000Z"

export const seedCriteria: ReadonlyArray<Criterion> = [
  {
    id: "empathy",
    name: "Empathy & active listening",
    description: "Recognizes the customer’s emotion and responds to what they actually said.",
    weight: 25,
    levels: ["Dismissive", "Minimal acknowledgment", "Adequate", "Strong", "Exceptional"],
    enabled: true,
    updatedAt,
  },
  {
    id: "accuracy",
    name: "Accuracy & policy alignment",
    description: "Gives accurate, internally consistent guidance, follows identity and security verification requirements, and avoids unsupported promises.",
    weight: 25,
    levels: ["Materially incorrect", "Multiple gaps", "Mostly accurate", "Accurate", "Precise and complete"],
    enabled: true,
    updatedAt,
  },
  {
    id: "resolution",
    name: "Resolution quality",
    description: "Moves the issue to a clear resolution or a well-owned next step.",
    weight: 30,
    levels: ["Unresolved", "Weak next step", "Partial resolution", "Resolved", "Resolved with proactive follow-through"],
    enabled: true,
    updatedAt,
  },
  {
    id: "communication",
    name: "Clear communication",
    description: "Uses concise, understandable language and confirms important details.",
    weight: 20,
    levels: ["Confusing", "Often unclear", "Understandable", "Clear", "Exceptionally clear"],
    enabled: true,
    updatedAt,
  },
]
